FROM mcr.microsoft.com/dotnet/aspnet:8.0
ARG ARG_CS_HELLO_WORLD_AES_KEY=""
ENV TZ=Asia/Shanghai
ENV DOTNET_ENVIRONMENT=prd
ENV DOTNET_HTTP_PORTS=8080
ENV CS_HELLO_WORLD_AES_KEY=$ARG_CS_HELLO_WORLD_AES_KEY

WORKDIR /app
COPY ./publish/* /app/
ENTRYPOINT dotnet cs-hello-world.dll
EXPOSE 8080
